format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$line_break\
$jobs\
$status\
${custom.character_normal}\
${custom.character_root}\
"""

[username]
format = "[$user]($style)@"
detect_env_vars = ["container"]

[hostname]
format = "[$hostname]($style) in "
detect_env_vars = ["container"]
ssh_only = false

[git_branch]
symbol = ""

[fill]
symbol = "\u2500"
style = "dimmed blue"

[status]
format = "[$status]($style) "
disabled = false

[custom.character_normal]
symbol = '\$ '
style = "green"
when = '[ "$(id -u)" -ne 0 ]'

[custom.character_root]
symbol = '# '
style = "bold red"
when = '[ "$(id -u)" -eq 0 ]'
