format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$line_break\
$jobs\
$status\
$character"""

[git_branch]
symbol = ""

[fill]
symbol = "\u2500"
style = "green"

[status]
format = "[$status]($style) "
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
