format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$line_break\
$jobs\
$status\
${custom.character}"""

[username]
format = "[$user]($style)@"
detect_env_vars = ["container"]

[hostname]
format = "[$hostname]($style) in "
detect_env_vars = ["container"]
ssh_only = false

[git_branch]
symbol = ""

[fill]
symbol = "\u2500"
style = "green"

[status]
format = "[$status]($style) "
disabled = false

[custom.character]
command = 'if [ "$(id -u)" -eq 0 ]; then printf "#"; else printf "%%"; fi'
when = true
